spring.application.name=niagaraMcp
logging.level.org.springframework.ai=DEBUG
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.streamable-http.enabled=true
spring.ai.mcp.server.streamable-http.path=/mcp
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.org.springframework.web=TRACE
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.sse.enabled=false
